"""Actual HDF5 success-timeline falsification against the executable Kaggle runner.

Only tiny synthetic HDF5 files are generated by this test. They have the
exact native RecordEpisode success/actions/JSON structure from frozen
ManiSkill #1495's record.py, but are NOT real physics rollout data.

The test loads the function from the EXACT source AST of the standalone
Kaggle entrypoint. This avoids a shadow copy of the auditor where a test
could pass while the production script has drifted.
"""
from __future__ import annotations

import ast
import json
from pathlib import Path
from tempfile import TemporaryDirectory
import unittest

import h5py


ENTRY = Path(__file__).resolve().parents[1] / "run_assay_factorial.py"


def source_exact_indexer():
    text = ENTRY.read_text(encoding="utf-8")
    syntax = ast.parse(text, filename=str(ENTRY))
    targets = [
        node for node in syntax.body
        if isinstance(node, ast.FunctionDef)
        and node.name == "index_converted_episodes"
    ]
    if len(targets) != 1:
        raise AssertionError("exactly one native result auditor is required")
    executable = ast.fix_missing_locations(
        ast.Module(body=targets, type_ignores=[])
    )
    namespace = {"json": json, "Path": Path}
    exec(compile(executable, str(ENTRY), "exec"), namespace)
    return namespace["index_converted_episodes"]


class NativeHdf5LabelTests(unittest.TestCase):
    def setUp(self):
        self.temp = TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.h5_path = self.root / "replay.h5"
        self.json_path = self.root / "replay.json"
        self.episodes = [
            {"episode_id": 0, "episode_seed": 11, "success": True,
             "elapsed_steps": 2},
            {"episode_id": 1, "episode_seed": 22, "success": False,
             "elapsed_steps": 2},
        ]
        self.save_meta()
        with h5py.File(self.h5_path, "w") as file:
            for episode in self.episodes:
                grp = file.create_group(f"traj_{episode['episode_id']}")
                grp.create_dataset("actions", data=[[0.1], [0.2]])
                grp.create_dataset("success",
                    data=[False, episode["success"]], dtype=bool)
        self.audit = source_exact_indexer()

    def save_meta(self):
        self.json_path.write_text(json.dumps({"episodes": self.episodes}),
                                  encoding="utf-8")

    def assert_denied(self, message):
        with self.assertRaisesRegex(RuntimeError, message):
            self.audit(self.h5_path)

    def test_true_native_terminal_only_selects_one_success(self):
        indexed = self.audit(self.h5_path)
        self.assertEqual(set(indexed), {11})
        self.assertEqual(indexed[11]["source_key"], "traj_0")
        self.assertTrue(indexed[11]["native_terminal_success"])

    def test_attacker_flips_failure_json_to_success_is_denied(self):
        self.episodes[1]["success"] = True
        self.save_meta()
        self.assert_denied("JSON success conflicts with HDF5 terminal outcome")

    def test_attacker_flips_success_json_to_failure_is_denied(self):
        self.episodes[0]["success"] = False
        self.save_meta()
        self.assert_denied("JSON success conflicts with HDF5 terminal outcome")

    def test_missing_native_hdf5_trajectory_is_not_measured_failure(self):
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_1"]
        self.assert_denied("missing HDF5")

    def test_missing_per_step_success_is_not_inferred_from_json(self):
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_1"]["success"]
        self.assert_denied("missing native per-step success/actions")

    def test_missing_action_sequence_denied(self):
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_0"]["actions"]
        self.assert_denied("missing native per-step success/actions")

    def test_success_timeline_missing_last_step_denied(self):
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_0"]["success"]
            file["traj_0"].create_dataset("success", data=[False], dtype=bool)
        self.assert_denied("corrupt/misaligned native outcome timeline")

    def test_non_boolean_native_outcome_denied(self):
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_1"]["success"]
            file["traj_1"].create_dataset("success", data=[0, 1], dtype="i4")
        self.assert_denied("corrupt/misaligned native outcome timeline")

    def test_json_duplicate_source_episode_seed_denied(self):
        self.episodes[1]["episode_seed"] = 11
        self.save_meta()
        self.assert_denied("duplicate converted episode seed")

    def test_native_zero_success_is_still_a_valid_measured_zero(self):
        self.episodes[0]["success"] = False
        self.save_meta()
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_0"]["success"]
            file["traj_0"].create_dataset("success", data=[False, False], dtype=bool)
        self.assertEqual(self.audit(self.h5_path), {})

    def test_progressive_success_is_not_automatically_terminal_success(self):
        self.episodes[1]["success"] = False
        self.save_meta()
        with h5py.File(self.h5_path, "a") as file:
            del file["traj_1"]["success"]
            file["traj_1"].create_dataset("success", data=[True, False], dtype=bool)
        self.assertEqual(set(self.audit(self.h5_path)), {11})

    def test_terminal_length_metadata_mismatch_denied(self):
        self.episodes[0]["elapsed_steps"] = 999
        self.save_meta()
        self.assert_denied("corrupt/misaligned native outcome timeline")


if __name__ == "__main__":
    unittest.main()
